/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedCrmRouteRouteImport } from './routes/_authenticated/crm/route'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates.index'
import { Route as AuthenticatedProposalsIndexRouteImport } from './routes/_authenticated/proposals.index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm/index'
import { Route as AuthenticatedTemplatesNewRouteImport } from './routes/_authenticated/templates.new'
import { Route as AuthenticatedTemplatesIdRouteImport } from './routes/_authenticated/templates.$id'
import { Route as AuthenticatedSettingsTermsRouteImport } from './routes/_authenticated/settings.terms'
import { Route as AuthenticatedSettingsRulesRouteImport } from './routes/_authenticated/settings.rules'
import { Route as AuthenticatedSettingsProductsRouteImport } from './routes/_authenticated/settings.products'
import { Route as AuthenticatedSettingsContentRouteImport } from './routes/_authenticated/settings.content'
import { Route as AuthenticatedProposalsNewRouteImport } from './routes/_authenticated/proposals.new'
import { Route as AuthenticatedProposalsIdRouteImport } from './routes/_authenticated/proposals.$id'
import { Route as AuthenticatedCrmToursIndexRouteImport } from './routes/_authenticated/crm/tours.index'
import { Route as AuthenticatedCrmQuotationsIndexRouteImport } from './routes/_authenticated/crm/quotations.index'
import { Route as AuthenticatedCrmProductsIndexRouteImport } from './routes/_authenticated/crm/products.index'
import { Route as AuthenticatedCrmOrdersIndexRouteImport } from './routes/_authenticated/crm/orders.index'
import { Route as AuthenticatedCrmLeadsIndexRouteImport } from './routes/_authenticated/crm/leads.index'
import { Route as AuthenticatedCrmFollowupsIndexRouteImport } from './routes/_authenticated/crm/followups.index'
import { Route as AuthenticatedCrmCompaniesIndexRouteImport } from './routes/_authenticated/crm/companies.index'
import { Route as AuthenticatedProposalsIdEditRouteImport } from './routes/_authenticated/proposals.$id.edit'
import { Route as AuthenticatedCrmQuotationsNewRouteImport } from './routes/_authenticated/crm/quotations.new'
import { Route as AuthenticatedCrmQuotationsIdRouteImport } from './routes/_authenticated/crm/quotations.$id'
import { Route as AuthenticatedCrmLeadsNewRouteImport } from './routes/_authenticated/crm/leads.new'
import { Route as AuthenticatedCrmLeadsIdRouteImport } from './routes/_authenticated/crm/leads.$id'
import { Route as AuthenticatedCrmCompaniesIdRouteImport } from './routes/_authenticated/crm/companies.$id'
import { Route as AuthenticatedCrmAdminUsersRouteImport } from './routes/_authenticated/crm/admin.users'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRouteRoute = AuthenticatedCrmRouteRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIndexRoute =
  AuthenticatedProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRouteRoute,
} as any)
const AuthenticatedTemplatesNewRoute =
  AuthenticatedTemplatesNewRouteImport.update({
    id: '/templates/new',
    path: '/templates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIdRoute =
  AuthenticatedTemplatesIdRouteImport.update({
    id: '/templates/$id',
    path: '/templates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsTermsRoute =
  AuthenticatedSettingsTermsRouteImport.update({
    id: '/settings/terms',
    path: '/settings/terms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRulesRoute =
  AuthenticatedSettingsRulesRouteImport.update({
    id: '/settings/rules',
    path: '/settings/rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProductsRoute =
  AuthenticatedSettingsProductsRouteImport.update({
    id: '/settings/products',
    path: '/settings/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsContentRoute =
  AuthenticatedSettingsContentRouteImport.update({
    id: '/settings/content',
    path: '/settings/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsNewRoute =
  AuthenticatedProposalsNewRouteImport.update({
    id: '/proposals/new',
    path: '/proposals/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIdRoute =
  AuthenticatedProposalsIdRouteImport.update({
    id: '/proposals/$id',
    path: '/proposals/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmToursIndexRoute =
  AuthenticatedCrmToursIndexRouteImport.update({
    id: '/tours/',
    path: '/tours/',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmQuotationsIndexRoute =
  AuthenticatedCrmQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmProductsIndexRoute =
  AuthenticatedCrmProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmOrdersIndexRoute =
  AuthenticatedCrmOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmLeadsIndexRoute =
  AuthenticatedCrmLeadsIndexRouteImport.update({
    id: '/leads/',
    path: '/leads/',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmFollowupsIndexRoute =
  AuthenticatedCrmFollowupsIndexRouteImport.update({
    id: '/followups/',
    path: '/followups/',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmCompaniesIndexRoute =
  AuthenticatedCrmCompaniesIndexRouteImport.update({
    id: '/companies/',
    path: '/companies/',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedProposalsIdEditRoute =
  AuthenticatedProposalsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedProposalsIdRoute,
  } as any)
const AuthenticatedCrmQuotationsNewRoute =
  AuthenticatedCrmQuotationsNewRouteImport.update({
    id: '/quotations/new',
    path: '/quotations/new',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmQuotationsIdRoute =
  AuthenticatedCrmQuotationsIdRouteImport.update({
    id: '/quotations/$id',
    path: '/quotations/$id',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmLeadsNewRoute =
  AuthenticatedCrmLeadsNewRouteImport.update({
    id: '/leads/new',
    path: '/leads/new',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmLeadsIdRoute = AuthenticatedCrmLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedCrmRouteRoute,
} as any)
const AuthenticatedCrmCompaniesIdRoute =
  AuthenticatedCrmCompaniesIdRouteImport.update({
    id: '/companies/$id',
    path: '/companies/$id',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)
const AuthenticatedCrmAdminUsersRoute =
  AuthenticatedCrmAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedCrmRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/crm': typeof AuthenticatedCrmRouteRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRouteWithChildren
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/settings/content': typeof AuthenticatedSettingsContentRoute
  '/settings/products': typeof AuthenticatedSettingsProductsRoute
  '/settings/rules': typeof AuthenticatedSettingsRulesRoute
  '/settings/terms': typeof AuthenticatedSettingsTermsRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/crm/admin/users': typeof AuthenticatedCrmAdminUsersRoute
  '/crm/companies/$id': typeof AuthenticatedCrmCompaniesIdRoute
  '/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/crm/leads/new': typeof AuthenticatedCrmLeadsNewRoute
  '/crm/quotations/$id': typeof AuthenticatedCrmQuotationsIdRoute
  '/crm/quotations/new': typeof AuthenticatedCrmQuotationsNewRoute
  '/proposals/$id/edit': typeof AuthenticatedProposalsIdEditRoute
  '/crm/companies/': typeof AuthenticatedCrmCompaniesIndexRoute
  '/crm/followups/': typeof AuthenticatedCrmFollowupsIndexRoute
  '/crm/leads/': typeof AuthenticatedCrmLeadsIndexRoute
  '/crm/orders/': typeof AuthenticatedCrmOrdersIndexRoute
  '/crm/products/': typeof AuthenticatedCrmProductsIndexRoute
  '/crm/quotations/': typeof AuthenticatedCrmQuotationsIndexRoute
  '/crm/tours/': typeof AuthenticatedCrmToursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRouteWithChildren
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/settings/content': typeof AuthenticatedSettingsContentRoute
  '/settings/products': typeof AuthenticatedSettingsProductsRoute
  '/settings/rules': typeof AuthenticatedSettingsRulesRoute
  '/settings/terms': typeof AuthenticatedSettingsTermsRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/proposals': typeof AuthenticatedProposalsIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/crm/admin/users': typeof AuthenticatedCrmAdminUsersRoute
  '/crm/companies/$id': typeof AuthenticatedCrmCompaniesIdRoute
  '/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/crm/leads/new': typeof AuthenticatedCrmLeadsNewRoute
  '/crm/quotations/$id': typeof AuthenticatedCrmQuotationsIdRoute
  '/crm/quotations/new': typeof AuthenticatedCrmQuotationsNewRoute
  '/proposals/$id/edit': typeof AuthenticatedProposalsIdEditRoute
  '/crm/companies': typeof AuthenticatedCrmCompaniesIndexRoute
  '/crm/followups': typeof AuthenticatedCrmFollowupsIndexRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsIndexRoute
  '/crm/orders': typeof AuthenticatedCrmOrdersIndexRoute
  '/crm/products': typeof AuthenticatedCrmProductsIndexRoute
  '/crm/quotations': typeof AuthenticatedCrmQuotationsIndexRoute
  '/crm/tours': typeof AuthenticatedCrmToursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/proposals/$id': typeof AuthenticatedProposalsIdRouteWithChildren
  '/_authenticated/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/_authenticated/settings/content': typeof AuthenticatedSettingsContentRoute
  '/_authenticated/settings/products': typeof AuthenticatedSettingsProductsRoute
  '/_authenticated/settings/rules': typeof AuthenticatedSettingsRulesRoute
  '/_authenticated/settings/terms': typeof AuthenticatedSettingsTermsRoute
  '/_authenticated/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/_authenticated/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/crm/admin/users': typeof AuthenticatedCrmAdminUsersRoute
  '/_authenticated/crm/companies/$id': typeof AuthenticatedCrmCompaniesIdRoute
  '/_authenticated/crm/leads/$id': typeof AuthenticatedCrmLeadsIdRoute
  '/_authenticated/crm/leads/new': typeof AuthenticatedCrmLeadsNewRoute
  '/_authenticated/crm/quotations/$id': typeof AuthenticatedCrmQuotationsIdRoute
  '/_authenticated/crm/quotations/new': typeof AuthenticatedCrmQuotationsNewRoute
  '/_authenticated/proposals/$id/edit': typeof AuthenticatedProposalsIdEditRoute
  '/_authenticated/crm/companies/': typeof AuthenticatedCrmCompaniesIndexRoute
  '/_authenticated/crm/followups/': typeof AuthenticatedCrmFollowupsIndexRoute
  '/_authenticated/crm/leads/': typeof AuthenticatedCrmLeadsIndexRoute
  '/_authenticated/crm/orders/': typeof AuthenticatedCrmOrdersIndexRoute
  '/_authenticated/crm/products/': typeof AuthenticatedCrmProductsIndexRoute
  '/_authenticated/crm/quotations/': typeof AuthenticatedCrmQuotationsIndexRoute
  '/_authenticated/crm/tours/': typeof AuthenticatedCrmToursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/crm'
    | '/customers'
    | '/dashboard'
    | '/proposals/$id'
    | '/proposals/new'
    | '/settings/content'
    | '/settings/products'
    | '/settings/rules'
    | '/settings/terms'
    | '/templates/$id'
    | '/templates/new'
    | '/crm/'
    | '/proposals/'
    | '/templates/'
    | '/crm/admin/users'
    | '/crm/companies/$id'
    | '/crm/leads/$id'
    | '/crm/leads/new'
    | '/crm/quotations/$id'
    | '/crm/quotations/new'
    | '/proposals/$id/edit'
    | '/crm/companies/'
    | '/crm/followups/'
    | '/crm/leads/'
    | '/crm/orders/'
    | '/crm/products/'
    | '/crm/quotations/'
    | '/crm/tours/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/customers'
    | '/dashboard'
    | '/proposals/$id'
    | '/proposals/new'
    | '/settings/content'
    | '/settings/products'
    | '/settings/rules'
    | '/settings/terms'
    | '/templates/$id'
    | '/templates/new'
    | '/crm'
    | '/proposals'
    | '/templates'
    | '/crm/admin/users'
    | '/crm/companies/$id'
    | '/crm/leads/$id'
    | '/crm/leads/new'
    | '/crm/quotations/$id'
    | '/crm/quotations/new'
    | '/proposals/$id/edit'
    | '/crm/companies'
    | '/crm/followups'
    | '/crm/leads'
    | '/crm/orders'
    | '/crm/products'
    | '/crm/quotations'
    | '/crm/tours'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/crm'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/proposals/$id'
    | '/_authenticated/proposals/new'
    | '/_authenticated/settings/content'
    | '/_authenticated/settings/products'
    | '/_authenticated/settings/rules'
    | '/_authenticated/settings/terms'
    | '/_authenticated/templates/$id'
    | '/_authenticated/templates/new'
    | '/_authenticated/crm/'
    | '/_authenticated/proposals/'
    | '/_authenticated/templates/'
    | '/_authenticated/crm/admin/users'
    | '/_authenticated/crm/companies/$id'
    | '/_authenticated/crm/leads/$id'
    | '/_authenticated/crm/leads/new'
    | '/_authenticated/crm/quotations/$id'
    | '/_authenticated/crm/quotations/new'
    | '/_authenticated/proposals/$id/edit'
    | '/_authenticated/crm/companies/'
    | '/_authenticated/crm/followups/'
    | '/_authenticated/crm/leads/'
    | '/_authenticated/crm/orders/'
    | '/_authenticated/crm/products/'
    | '/_authenticated/crm/quotations/'
    | '/_authenticated/crm/tours/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/': {
      id: '/_authenticated/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AuthenticatedProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/templates/new': {
      id: '/_authenticated/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AuthenticatedTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/$id': {
      id: '/_authenticated/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AuthenticatedTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/terms': {
      id: '/_authenticated/settings/terms'
      path: '/settings/terms'
      fullPath: '/settings/terms'
      preLoaderRoute: typeof AuthenticatedSettingsTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/rules': {
      id: '/_authenticated/settings/rules'
      path: '/settings/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof AuthenticatedSettingsRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/products': {
      id: '/_authenticated/settings/products'
      path: '/settings/products'
      fullPath: '/settings/products'
      preLoaderRoute: typeof AuthenticatedSettingsProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/content': {
      id: '/_authenticated/settings/content'
      path: '/settings/content'
      fullPath: '/settings/content'
      preLoaderRoute: typeof AuthenticatedSettingsContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/new': {
      id: '/_authenticated/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AuthenticatedProposalsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/$id': {
      id: '/_authenticated/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof AuthenticatedProposalsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/tours/': {
      id: '/_authenticated/crm/tours/'
      path: '/tours'
      fullPath: '/crm/tours/'
      preLoaderRoute: typeof AuthenticatedCrmToursIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/quotations/': {
      id: '/_authenticated/crm/quotations/'
      path: '/quotations'
      fullPath: '/crm/quotations/'
      preLoaderRoute: typeof AuthenticatedCrmQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/products/': {
      id: '/_authenticated/crm/products/'
      path: '/products'
      fullPath: '/crm/products/'
      preLoaderRoute: typeof AuthenticatedCrmProductsIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/orders/': {
      id: '/_authenticated/crm/orders/'
      path: '/orders'
      fullPath: '/crm/orders/'
      preLoaderRoute: typeof AuthenticatedCrmOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/leads/': {
      id: '/_authenticated/crm/leads/'
      path: '/leads'
      fullPath: '/crm/leads/'
      preLoaderRoute: typeof AuthenticatedCrmLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/followups/': {
      id: '/_authenticated/crm/followups/'
      path: '/followups'
      fullPath: '/crm/followups/'
      preLoaderRoute: typeof AuthenticatedCrmFollowupsIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/companies/': {
      id: '/_authenticated/crm/companies/'
      path: '/companies'
      fullPath: '/crm/companies/'
      preLoaderRoute: typeof AuthenticatedCrmCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/proposals/$id/edit': {
      id: '/_authenticated/proposals/$id/edit'
      path: '/edit'
      fullPath: '/proposals/$id/edit'
      preLoaderRoute: typeof AuthenticatedProposalsIdEditRouteImport
      parentRoute: typeof AuthenticatedProposalsIdRoute
    }
    '/_authenticated/crm/quotations/new': {
      id: '/_authenticated/crm/quotations/new'
      path: '/quotations/new'
      fullPath: '/crm/quotations/new'
      preLoaderRoute: typeof AuthenticatedCrmQuotationsNewRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/quotations/$id': {
      id: '/_authenticated/crm/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/crm/quotations/$id'
      preLoaderRoute: typeof AuthenticatedCrmQuotationsIdRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/leads/new': {
      id: '/_authenticated/crm/leads/new'
      path: '/leads/new'
      fullPath: '/crm/leads/new'
      preLoaderRoute: typeof AuthenticatedCrmLeadsNewRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/leads/$id': {
      id: '/_authenticated/crm/leads/$id'
      path: '/leads/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof AuthenticatedCrmLeadsIdRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/companies/$id': {
      id: '/_authenticated/crm/companies/$id'
      path: '/companies/$id'
      fullPath: '/crm/companies/$id'
      preLoaderRoute: typeof AuthenticatedCrmCompaniesIdRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
    '/_authenticated/crm/admin/users': {
      id: '/_authenticated/crm/admin/users'
      path: '/admin/users'
      fullPath: '/crm/admin/users'
      preLoaderRoute: typeof AuthenticatedCrmAdminUsersRouteImport
      parentRoute: typeof AuthenticatedCrmRouteRoute
    }
  }
}

interface AuthenticatedCrmRouteRouteChildren {
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedCrmAdminUsersRoute: typeof AuthenticatedCrmAdminUsersRoute
  AuthenticatedCrmCompaniesIdRoute: typeof AuthenticatedCrmCompaniesIdRoute
  AuthenticatedCrmLeadsIdRoute: typeof AuthenticatedCrmLeadsIdRoute
  AuthenticatedCrmLeadsNewRoute: typeof AuthenticatedCrmLeadsNewRoute
  AuthenticatedCrmQuotationsIdRoute: typeof AuthenticatedCrmQuotationsIdRoute
  AuthenticatedCrmQuotationsNewRoute: typeof AuthenticatedCrmQuotationsNewRoute
  AuthenticatedCrmCompaniesIndexRoute: typeof AuthenticatedCrmCompaniesIndexRoute
  AuthenticatedCrmFollowupsIndexRoute: typeof AuthenticatedCrmFollowupsIndexRoute
  AuthenticatedCrmLeadsIndexRoute: typeof AuthenticatedCrmLeadsIndexRoute
  AuthenticatedCrmOrdersIndexRoute: typeof AuthenticatedCrmOrdersIndexRoute
  AuthenticatedCrmProductsIndexRoute: typeof AuthenticatedCrmProductsIndexRoute
  AuthenticatedCrmQuotationsIndexRoute: typeof AuthenticatedCrmQuotationsIndexRoute
  AuthenticatedCrmToursIndexRoute: typeof AuthenticatedCrmToursIndexRoute
}

const AuthenticatedCrmRouteRouteChildren: AuthenticatedCrmRouteRouteChildren = {
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedCrmAdminUsersRoute: AuthenticatedCrmAdminUsersRoute,
  AuthenticatedCrmCompaniesIdRoute: AuthenticatedCrmCompaniesIdRoute,
  AuthenticatedCrmLeadsIdRoute: AuthenticatedCrmLeadsIdRoute,
  AuthenticatedCrmLeadsNewRoute: AuthenticatedCrmLeadsNewRoute,
  AuthenticatedCrmQuotationsIdRoute: AuthenticatedCrmQuotationsIdRoute,
  AuthenticatedCrmQuotationsNewRoute: AuthenticatedCrmQuotationsNewRoute,
  AuthenticatedCrmCompaniesIndexRoute: AuthenticatedCrmCompaniesIndexRoute,
  AuthenticatedCrmFollowupsIndexRoute: AuthenticatedCrmFollowupsIndexRoute,
  AuthenticatedCrmLeadsIndexRoute: AuthenticatedCrmLeadsIndexRoute,
  AuthenticatedCrmOrdersIndexRoute: AuthenticatedCrmOrdersIndexRoute,
  AuthenticatedCrmProductsIndexRoute: AuthenticatedCrmProductsIndexRoute,
  AuthenticatedCrmQuotationsIndexRoute: AuthenticatedCrmQuotationsIndexRoute,
  AuthenticatedCrmToursIndexRoute: AuthenticatedCrmToursIndexRoute,
}

const AuthenticatedCrmRouteRouteWithChildren =
  AuthenticatedCrmRouteRoute._addFileChildren(
    AuthenticatedCrmRouteRouteChildren,
  )

interface AuthenticatedProposalsIdRouteChildren {
  AuthenticatedProposalsIdEditRoute: typeof AuthenticatedProposalsIdEditRoute
}

const AuthenticatedProposalsIdRouteChildren: AuthenticatedProposalsIdRouteChildren =
  {
    AuthenticatedProposalsIdEditRoute: AuthenticatedProposalsIdEditRoute,
  }

const AuthenticatedProposalsIdRouteWithChildren =
  AuthenticatedProposalsIdRoute._addFileChildren(
    AuthenticatedProposalsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCrmRouteRoute: typeof AuthenticatedCrmRouteRouteWithChildren
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProposalsIdRoute: typeof AuthenticatedProposalsIdRouteWithChildren
  AuthenticatedProposalsNewRoute: typeof AuthenticatedProposalsNewRoute
  AuthenticatedSettingsContentRoute: typeof AuthenticatedSettingsContentRoute
  AuthenticatedSettingsProductsRoute: typeof AuthenticatedSettingsProductsRoute
  AuthenticatedSettingsRulesRoute: typeof AuthenticatedSettingsRulesRoute
  AuthenticatedSettingsTermsRoute: typeof AuthenticatedSettingsTermsRoute
  AuthenticatedTemplatesIdRoute: typeof AuthenticatedTemplatesIdRoute
  AuthenticatedTemplatesNewRoute: typeof AuthenticatedTemplatesNewRoute
  AuthenticatedProposalsIndexRoute: typeof AuthenticatedProposalsIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCrmRouteRoute: AuthenticatedCrmRouteRouteWithChildren,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProposalsIdRoute: AuthenticatedProposalsIdRouteWithChildren,
  AuthenticatedProposalsNewRoute: AuthenticatedProposalsNewRoute,
  AuthenticatedSettingsContentRoute: AuthenticatedSettingsContentRoute,
  AuthenticatedSettingsProductsRoute: AuthenticatedSettingsProductsRoute,
  AuthenticatedSettingsRulesRoute: AuthenticatedSettingsRulesRoute,
  AuthenticatedSettingsTermsRoute: AuthenticatedSettingsTermsRoute,
  AuthenticatedTemplatesIdRoute: AuthenticatedTemplatesIdRoute,
  AuthenticatedTemplatesNewRoute: AuthenticatedTemplatesNewRoute,
  AuthenticatedProposalsIndexRoute: AuthenticatedProposalsIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
