/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates.index'
import { Route as AuthenticatedProposalsIndexRouteImport } from './routes/_authenticated/proposals.index'
import { Route as AuthenticatedTemplatesNewRouteImport } from './routes/_authenticated/templates.new'
import { Route as AuthenticatedTemplatesIdRouteImport } from './routes/_authenticated/templates.$id'
import { Route as AuthenticatedSettingsTermsRouteImport } from './routes/_authenticated/settings.terms'
import { Route as AuthenticatedSettingsRulesRouteImport } from './routes/_authenticated/settings.rules'
import { Route as AuthenticatedSettingsProductsRouteImport } from './routes/_authenticated/settings.products'
import { Route as AuthenticatedSettingsContentRouteImport } from './routes/_authenticated/settings.content'
import { Route as AuthenticatedProposalsNewRouteImport } from './routes/_authenticated/proposals.new'
import { Route as AuthenticatedProposalsIdRouteImport } from './routes/_authenticated/proposals.$id'
import { Route as AuthenticatedProposalsIdEditRouteImport } from './routes/_authenticated/proposals.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIndexRoute =
  AuthenticatedProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesNewRoute =
  AuthenticatedTemplatesNewRouteImport.update({
    id: '/templates/new',
    path: '/templates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesIdRoute =
  AuthenticatedTemplatesIdRouteImport.update({
    id: '/templates/$id',
    path: '/templates/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsTermsRoute =
  AuthenticatedSettingsTermsRouteImport.update({
    id: '/settings/terms',
    path: '/settings/terms',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRulesRoute =
  AuthenticatedSettingsRulesRouteImport.update({
    id: '/settings/rules',
    path: '/settings/rules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsProductsRoute =
  AuthenticatedSettingsProductsRouteImport.update({
    id: '/settings/products',
    path: '/settings/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsContentRoute =
  AuthenticatedSettingsContentRouteImport.update({
    id: '/settings/content',
    path: '/settings/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsNewRoute =
  AuthenticatedProposalsNewRouteImport.update({
    id: '/proposals/new',
    path: '/proposals/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIdRoute =
  AuthenticatedProposalsIdRouteImport.update({
    id: '/proposals/$id',
    path: '/proposals/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProposalsIdEditRoute =
  AuthenticatedProposalsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedProposalsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRouteWithChildren
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/settings/content': typeof AuthenticatedSettingsContentRoute
  '/settings/products': typeof AuthenticatedSettingsProductsRoute
  '/settings/rules': typeof AuthenticatedSettingsRulesRoute
  '/settings/terms': typeof AuthenticatedSettingsTermsRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/proposals/$id/edit': typeof AuthenticatedProposalsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/proposals/$id': typeof AuthenticatedProposalsIdRouteWithChildren
  '/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/settings/content': typeof AuthenticatedSettingsContentRoute
  '/settings/products': typeof AuthenticatedSettingsProductsRoute
  '/settings/rules': typeof AuthenticatedSettingsRulesRoute
  '/settings/terms': typeof AuthenticatedSettingsTermsRoute
  '/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/proposals': typeof AuthenticatedProposalsIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/proposals/$id/edit': typeof AuthenticatedProposalsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/proposals/$id': typeof AuthenticatedProposalsIdRouteWithChildren
  '/_authenticated/proposals/new': typeof AuthenticatedProposalsNewRoute
  '/_authenticated/settings/content': typeof AuthenticatedSettingsContentRoute
  '/_authenticated/settings/products': typeof AuthenticatedSettingsProductsRoute
  '/_authenticated/settings/rules': typeof AuthenticatedSettingsRulesRoute
  '/_authenticated/settings/terms': typeof AuthenticatedSettingsTermsRoute
  '/_authenticated/templates/$id': typeof AuthenticatedTemplatesIdRoute
  '/_authenticated/templates/new': typeof AuthenticatedTemplatesNewRoute
  '/_authenticated/proposals/': typeof AuthenticatedProposalsIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/proposals/$id/edit': typeof AuthenticatedProposalsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/customers'
    | '/dashboard'
    | '/proposals/$id'
    | '/proposals/new'
    | '/settings/content'
    | '/settings/products'
    | '/settings/rules'
    | '/settings/terms'
    | '/templates/$id'
    | '/templates/new'
    | '/proposals/'
    | '/templates/'
    | '/proposals/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/customers'
    | '/dashboard'
    | '/proposals/$id'
    | '/proposals/new'
    | '/settings/content'
    | '/settings/products'
    | '/settings/rules'
    | '/settings/terms'
    | '/templates/$id'
    | '/templates/new'
    | '/proposals'
    | '/templates'
    | '/proposals/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/proposals/$id'
    | '/_authenticated/proposals/new'
    | '/_authenticated/settings/content'
    | '/_authenticated/settings/products'
    | '/_authenticated/settings/rules'
    | '/_authenticated/settings/terms'
    | '/_authenticated/templates/$id'
    | '/_authenticated/templates/new'
    | '/_authenticated/proposals/'
    | '/_authenticated/templates/'
    | '/_authenticated/proposals/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/': {
      id: '/_authenticated/proposals/'
      path: '/proposals'
      fullPath: '/proposals/'
      preLoaderRoute: typeof AuthenticatedProposalsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/new': {
      id: '/_authenticated/templates/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AuthenticatedTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates/$id': {
      id: '/_authenticated/templates/$id'
      path: '/templates/$id'
      fullPath: '/templates/$id'
      preLoaderRoute: typeof AuthenticatedTemplatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/terms': {
      id: '/_authenticated/settings/terms'
      path: '/settings/terms'
      fullPath: '/settings/terms'
      preLoaderRoute: typeof AuthenticatedSettingsTermsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/rules': {
      id: '/_authenticated/settings/rules'
      path: '/settings/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof AuthenticatedSettingsRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/products': {
      id: '/_authenticated/settings/products'
      path: '/settings/products'
      fullPath: '/settings/products'
      preLoaderRoute: typeof AuthenticatedSettingsProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/content': {
      id: '/_authenticated/settings/content'
      path: '/settings/content'
      fullPath: '/settings/content'
      preLoaderRoute: typeof AuthenticatedSettingsContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/new': {
      id: '/_authenticated/proposals/new'
      path: '/proposals/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof AuthenticatedProposalsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/$id': {
      id: '/_authenticated/proposals/$id'
      path: '/proposals/$id'
      fullPath: '/proposals/$id'
      preLoaderRoute: typeof AuthenticatedProposalsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proposals/$id/edit': {
      id: '/_authenticated/proposals/$id/edit'
      path: '/edit'
      fullPath: '/proposals/$id/edit'
      preLoaderRoute: typeof AuthenticatedProposalsIdEditRouteImport
      parentRoute: typeof AuthenticatedProposalsIdRoute
    }
  }
}

interface AuthenticatedProposalsIdRouteChildren {
  AuthenticatedProposalsIdEditRoute: typeof AuthenticatedProposalsIdEditRoute
}

const AuthenticatedProposalsIdRouteChildren: AuthenticatedProposalsIdRouteChildren =
  {
    AuthenticatedProposalsIdEditRoute: AuthenticatedProposalsIdEditRoute,
  }

const AuthenticatedProposalsIdRouteWithChildren =
  AuthenticatedProposalsIdRoute._addFileChildren(
    AuthenticatedProposalsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProposalsIdRoute: typeof AuthenticatedProposalsIdRouteWithChildren
  AuthenticatedProposalsNewRoute: typeof AuthenticatedProposalsNewRoute
  AuthenticatedSettingsContentRoute: typeof AuthenticatedSettingsContentRoute
  AuthenticatedSettingsProductsRoute: typeof AuthenticatedSettingsProductsRoute
  AuthenticatedSettingsRulesRoute: typeof AuthenticatedSettingsRulesRoute
  AuthenticatedSettingsTermsRoute: typeof AuthenticatedSettingsTermsRoute
  AuthenticatedTemplatesIdRoute: typeof AuthenticatedTemplatesIdRoute
  AuthenticatedTemplatesNewRoute: typeof AuthenticatedTemplatesNewRoute
  AuthenticatedProposalsIndexRoute: typeof AuthenticatedProposalsIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProposalsIdRoute: AuthenticatedProposalsIdRouteWithChildren,
  AuthenticatedProposalsNewRoute: AuthenticatedProposalsNewRoute,
  AuthenticatedSettingsContentRoute: AuthenticatedSettingsContentRoute,
  AuthenticatedSettingsProductsRoute: AuthenticatedSettingsProductsRoute,
  AuthenticatedSettingsRulesRoute: AuthenticatedSettingsRulesRoute,
  AuthenticatedSettingsTermsRoute: AuthenticatedSettingsTermsRoute,
  AuthenticatedTemplatesIdRoute: AuthenticatedTemplatesIdRoute,
  AuthenticatedTemplatesNewRoute: AuthenticatedTemplatesNewRoute,
  AuthenticatedProposalsIndexRoute: AuthenticatedProposalsIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
